import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const generalSans = localFont({
  src: "./fonts/GeneralSans.woff",
  variable: "--font-general-sans",
  weight: "100 900",
});

const clashGrotesk = localFont({
  src: "./fonts/ClashGrotesk.woff",
  variable: "--font-clash-grotesk",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${generalSans.variable} ${clashGrotesk.variable}`}>
        {children}
      </body>
    </html>
  );
}
